export const PERMISSIONS = {
  PEOPLE_READ: 'PEOPLE_READ',
  PEOPLE_WRITE: 'PEOPLE_WRITE',
  COMPANIES_READ: 'COMPANIES_READ',
  COMPANIES_WRITE: 'COMPANIES_WRITE',
  BANK_ACCOUNTS_READ: 'BANK_ACCOUNTS_READ',
  BANK_ACCOUNTS_WRITE: 'BANK_ACCOUNTS_WRITE',
  DEVELOPMENTS_READ: 'DEVELOPMENTS_READ',
  DEVELOPMENTS_WRITE: 'DEVELOPMENTS_WRITE',
  UNITS_READ: 'UNITS_READ',
  UNITS_WRITE: 'UNITS_WRITE',
  PRICES_READ: 'PRICES_READ',
  PRICES_WRITE: 'PRICES_WRITE',
  INVESTMENTS_READ: 'INVESTMENTS_READ',
  INVESTMENTS_WRITE: 'INVESTMENTS_WRITE',
  RETURNS_READ: 'RETURNS_READ',
  RETURNS_WRITE: 'RETURNS_WRITE',
  DOCUMENTS_READ: 'DOCUMENTS_READ',
  DOCUMENTS_WRITE: 'DOCUMENTS_WRITE',
  INTERACTIONS_READ: 'INTERACTIONS_READ',
  INTERACTIONS_WRITE: 'INTERACTIONS_WRITE',
  DASHBOARD_READ: 'DASHBOARD_READ',
  REPORTS_EXPORT: 'REPORTS_EXPORT',
  USERS_MANAGE: 'USERS_MANAGE',
  AUDIT_READ: 'AUDIT_READ',
  CRM_READ: 'CRM_READ',
  CRM_WRITE: 'CRM_WRITE',
  SALES_READ: 'SALES_READ',
  SALES_WRITE: 'SALES_WRITE',
  FINANCE_READ: 'FINANCE_READ',
  FINANCE_WRITE: 'FINANCE_WRITE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: readonly Permission[] = Object.freeze(
  Object.values(PERMISSIONS),
);
